{{- if .Values.service.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ .Values.service.name }}
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
spec:
  endpoints:
    - interval: 30s
      targetPort: 8080
      path: {{ .Values.service.serviceMonitor.path }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
{{ end }}