name: Build Go project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'
          cache-dependency-path: go.sum
      - run: go version

      - name: Build project
        run: |
          CGO_ENABLED=1 go build -o kafka-app main.go
          go run main.go
